server:
  port: 8087

spring:
  ai:
    openai:
      api-key: AIzaSyCTeKNzA-OuojeSXjCTCYCZpVofRobdZG8
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash