server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service      
          predicates:
            - Path=/api/users/**

        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**

        - id: camera-service
          uri: lb://camera-service
          predicates:
            - Path=/api/cameras/**

        - id: analysis-service
          uri: lb://analysis-service
          predicates:
            - Path=/api/analysis/**
            
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/api/orders/**
#
#        - id: notification-service
#          uri: lb://notification-service
#          predicates:
#            - Path=/api/notifications/**

        # API Documentation routes
#        - id: user-service-docs
#          uri: lb://user-service
#          predicates:
#            - Path=/user-service/v3/api-docs
#          filters:
#            - RewritePath=/user-service/v3/api-docs, /v3/api-docs
#
#        - id: order-service-docs
#          uri: lb://order-service
#          predicates:
#            - Path=/order-service/v3/api-docs
#          filters:
#            - RewritePath=/order-service/v3/api-docs, /v3/api-docs
#
#        - id: notification-service-docs
#          uri: lb://notification-service
#          predicates:
#            - Path=/notification-service/v3/api-docs
#          filters:
#            - RewritePath=/notification-service/v3/api-docs, /v3/api-docs

#springdoc:
#  swagger-ui:
#    urls:
#      - name: user-service
#        url: /user-service/v3/api-docs
#      - name: order-service
#        url: /order-service/v3/api-docs
#      - name: notification-service
#        url: /notification-service/v3/api-docs
#    path: /swagger-ui.html
#  api-docs:
#    path: /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
